/**
 * ExperimentNotebook.js — Local Digital Lab Notebook (Sprint E2)
 *
 * Implements the 8-step scientific inquiry cycle:
 * Question → Predict → Method → Experiment → Observe → Interpret → Conclude → Reflect
 *
 * Zero backend. Auto-saves locally to Local Workspace Storage (localStorage).
 * Provides 1-tap Markdown and JSON export for learners.
 */

export class ExperimentNotebook {
  constructor(containerId = 'experiment-notebook-container') {
    this.containerId = containerId;
    this.STORAGE_KEY = 'val_experiment_notebook_v1';
    this.entries = this.loadEntries();
    this.activeId = null;
  }

  loadEntries() {
    try {
      const raw = localStorage.getItem(this.STORAGE_KEY);
      return raw ? JSON.parse(raw) : [];
    } catch (e) {
      console.warn('[Notebook] Failed to read from localStorage:', e);
      return [];
    }
  }

  saveEntries() {
    try {
      localStorage.setItem(this.STORAGE_KEY, JSON.stringify(this.entries));
    } catch (e) {
      console.warn('[Notebook] Failed to save to localStorage:', e);
    }
  }

  createNewEntry(sampleName = 'Mixture', methodParams = {}) {
    const newEntry = {
      id: 'exp_' + Date.now(),
      timestamp: new Date().toISOString(),
      sampleName,
      methodParams: { ...methodParams },
      question: 'Will changing mobile phase parameters improve resolution (Rs >= 1.5)?',
      prediction: 'Increasing % organic modifier should reduce retention time for all analytes.',
      observation: '',
      conclusion: '',
      reflection: '',
      runResult: null
    };

    this.entries.unshift(newEntry);
    this.activeId = newEntry.id;
    this.saveEntries();
    this.render();
    return newEntry;
  }

  attachRunResult(runId, runResult) {
    let entry = this.entries.find(e => e.id === this.activeId) || this.entries[0];
    if (!entry) {
      entry = this.createNewEntry('Current Run', runResult?.method || {});
    }

    entry.runResult = runResult;
    if (runResult?.peaks) {
      entry.observation = `Observed ${runResult.peaks.length} separated peaks. `;
      const minRs = Math.min(...runResult.peaks.map(p => p.resolution || 99));
      entry.observation += minRs < 1.5 ? `Minimum resolution Rs = ${minRs.toFixed(2)} (Suboptimal baseline separation).` : `All peaks baseline separated (Rs >= 1.5).`;
    }

    this.saveEntries();
    this.render();
  }

  updateActiveEntry(field, text) {
    const entry = this.entries.find(e => e.id === this.activeId) || this.entries[0];
    if (entry && field in entry) {
      entry[field] = text;
      this.saveEntries();
    }
  }

  exportMarkdown(entryId = this.activeId) {
    const entry = this.entries.find(e => e.id === entryId) || this.entries[0];
    if (!entry) return;

    const md = `# 🧪 Virtual Analytical Lab — Experiment Report
**Date:** ${new Date(entry.timestamp).toLocaleString()}  
**Sample:** ${entry.sampleName}  

---

## 1. Scientific Inquiry Cycle

### ❓ Question
${entry.question || 'N/A'}

### 🔮 Prediction
${entry.prediction || 'N/A'}

### 📈 Observation
${entry.observation || 'N/A'}

### 🎯 Conclusion
${entry.conclusion || 'N/A'}

### 💡 Reflection
${entry.reflection || 'N/A'}

---

## 2. Experimental Method Parameters
- **Flow Rate:** ${entry.methodParams.flowRate || 1.0} mL/min
- **Mobile Phase %B:** ${entry.methodParams.organicPercent || 40}%
- **Column Temp:** ${entry.methodParams.temperature || 25}°C
- **Buffer pH:** ${entry.methodParams.ph || 7.0}
- **UV Wavelength:** ${entry.methodParams.wavelength || 254} nm

---
*Generated by Virtual Analytical Lab (Standalone Educational Simulator)*
`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `experiment_report_${entry.id}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  render() {
    const container = document.getElementById(this.containerId);
    if (!container) return;

    const current = this.entries.find(e => e.id === this.activeId) || this.entries[0];
    if (!current) {
      container.innerHTML = `
        <div style="text-align:center; padding:30px; color:#64748b;">
          <p>No experiment notebook entries yet.</p>
          <button id="btnNewNotebook" style="padding:8px 16px; background:#38bdf8; color:#0f172a; font-weight:700; border:none; border-radius:6px; cursor:pointer;">+ Start New Entry</button>
        </div>
      `;
      // C1.2: use onclick (not addEventListener) — render() may be called multiple times,
      // re-creating this element each time. onclick overwrites; addEventListener accumulates.
      const newBtn = document.getElementById('btnNewNotebook');
      if (newBtn) newBtn.onclick = () => this.createNewEntry();
      return;
    }

    container.innerHTML = `
      <div style="background:#0f172a; border:1px solid rgba(56,189,248,0.2); border-radius:12px; padding:20px; color:#f8fafc; font-family:-apple-system,BlinkMacSystemFont,sans-serif;">
        <div style="display:flex; justify-content:space-between; align-items:center; border-bottom:1px solid rgba(255,255,255,0.1); padding-bottom:12px; margin-bottom:16px;">
          <div>
            <h3 style="margin:0; font-size:1.1rem; color:#38bdf8; display:flex; align-items:center; gap:8px;">
              <span>📓 Experiment Notebook</span>
            </h3>
            <div style="font-size:0.75rem; color:#64748b; margin-top:2px;">
              Auto-saved locally • ${new Date(current.timestamp).toLocaleTimeString()}
            </div>
          </div>

          <div style="display:flex; gap:8px;">
            <button id="btnExportMd" style="background:#1e293b; color:#38bdf8; border:1px solid rgba(56,189,248,0.3); padding:6px 12px; border-radius:6px; font-size:0.8rem; cursor:pointer; font-weight:600;">📥 Export Markdown</button>
            <button id="btnNewNotebook" style="background:#38bdf8; color:#0f172a; border:none; padding:6px 12px; border-radius:6px; font-size:0.8rem; cursor:pointer; font-weight:700;">+ New Entry</button>
          </div>
        </div>

        <div style="display:grid; grid-template-columns: 1fr; gap:14px;">
          <div>
            <label style="font-size:0.75rem; text-transform:uppercase; letter-spacing:0.05em; color:#38bdf8; font-weight:700; display:block; margin-bottom:4px;">1. Question</label>
            <textarea id="nbQuestion" style="width:100%; background:#1e293b; border:1px solid rgba(255,255,255,0.1); border-radius:6px; color:#f8fafc; padding:8px; font-size:0.88rem; resize:vertical; min-height:48px;">${current.question || ''}</textarea>
          </div>

          <div>
            <label style="font-size:0.75rem; text-transform:uppercase; letter-spacing:0.05em; color:#a78bfa; font-weight:700; display:block; margin-bottom:4px;">2. Prediction</label>
            <textarea id="nbPrediction" style="width:100%; background:#1e293b; border:1px solid rgba(255,255,255,0.1); border-radius:6px; color:#f8fafc; padding:8px; font-size:0.88rem; resize:vertical; min-height:48px;">${current.prediction || ''}</textarea>
          </div>

          <div>
            <label style="font-size:0.75rem; text-transform:uppercase; letter-spacing:0.05em; color:#34d399; font-weight:700; display:block; margin-bottom:4px;">3. Observation</label>
            <textarea id="nbObservation" style="width:100%; background:#1e293b; border:1px solid rgba(255,255,255,0.1); border-radius:6px; color:#f8fafc; padding:8px; font-size:0.88rem; resize:vertical; min-height:48px;">${current.observation || ''}</textarea>
          </div>

          <div style="display:grid; grid-template-columns:1fr 1fr; gap:12px;">
            <div>
              <label style="font-size:0.75rem; text-transform:uppercase; letter-spacing:0.05em; color:#fbbf24; font-weight:700; display:block; margin-bottom:4px;">4. Conclusion</label>
              <textarea id="nbConclusion" style="width:100%; background:#1e293b; border:1px solid rgba(255,255,255,0.1); border-radius:6px; color:#f8fafc; padding:8px; font-size:0.88rem; resize:vertical; min-height:48px;" placeholder="What did you learn?">${current.conclusion || ''}</textarea>
            </div>

            <div>
              <label style="font-size:0.75rem; text-transform:uppercase; letter-spacing:0.05em; color:#f472b6; font-weight:700; display:block; margin-bottom:4px;">5. Reflection</label>
              <textarea id="nbReflection" style="width:100%; background:#1e293b; border:1px solid rgba(255,255,255,0.1); border-radius:6px; color:#f8fafc; padding:8px; font-size:0.88rem; resize:vertical; min-height:48px;" placeholder="What would you adjust next?">${current.reflection || ''}</textarea>
            </div>
          </div>
        </div>
      </div>
    `;

    // Bind event listeners for auto-save
    ['Question', 'Prediction', 'Observation', 'Conclusion', 'Reflection'].forEach(field => {
      const el = document.getElementById(`nb${field}`);
      if (el) {
        el.addEventListener('input', (e) => {
          this.updateActiveEntry(field.toLowerCase(), e.target.value);
        });
      }
    });

    // C1.2: onclick assignment — safe across repeated render() calls.
    const exportBtn = document.getElementById('btnExportMd');
    const newEntryBtn = document.getElementById('btnNewNotebook');
    if (exportBtn)  exportBtn.onclick  = () => this.exportMarkdown();
    if (newEntryBtn) newEntryBtn.onclick = () => this.createNewEntry();
  }
}
